/// <reference types="@sveltejs/kit" />
/// <reference types="@cloudflare/workers-types" />

declare namespace App {
  interface Platform {
    env: {
      /** D1 database binding (from Wrangler config) */
      db?: D1Database
      /** Static assets binding generated by the adapter */
      ASSETS?: unknown
      /** Add other bindings here as needed */
    }
    ctx: ExecutionContext
  }
  interface PageData {
    auctionSize?: number
    seat?: number
    auctionId?: number
    colors: string[]
  }
}
